version: '2'

services:
    converter:
        ports:
            - "1-65535:1-65535"
        volumes:
            - ${LOGDIR}:/${LOGDIR}
        build: ./converter
        command: python3 main.py --use-google --json-keyfile ${JSON_KEYFILE} --spreadsheet ${SPREADSHEET_NAME} --logdir ${LOGDIR}
        restart: always

    logs_serving:
        ports:
            - "80:80"
        volumes:
            - ${LOGDIR}:/${LOGDIR}
        build: ./logs_serving
        command: python3 -m http.server ${LOGGER_PORT} --directory ${LOGDIR}
        restart: always
        depends_on:
            -   converter