version: '2'

services:
    converter:
        ports:
            - "10000-10200:10000-10200"
        volumes:
            - ${LOGDIR}:/logdir
            - ${JSON_KEYFILE}:/keyfile.json
        build: ./converter
        command: python3 main.py --use-google --json-keyfile keyfile.json --spreadsheet ${SPREADSHEET_NAME} --logdir /logdir
        restart: always

    logs_serving:
        ports:
            - "80:80"
        volumes:
            - ${LOGDIR}:/logdir
        build: ./logs_serving
        command: python3 -m http.server 80 --directory /logdir
        restart: always
        depends_on:
            -   converter